<?php
$options = [
	[
		'id' => 'form-text-box',
		'type' => 'text',
		'label' => 'TextBox',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => 'default value',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-text-readonly',
		'type' => 'text-readonly',
		'label' => 'TextBox (readonly)',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => 'default value',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-text-disabled',
		'type' => 'text-disabled',
		'label' => 'TextBox (disabled)',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => 'default value',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-text-number',
		'type' => 'number',
		'label' => 'Number',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => 'default value',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-text-email',
		'type' => 'email',
		'label' => 'Email',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => 'default value',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-text-url',
		'type' => 'url',
		'label' => 'URL',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => 'default value',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-text-password',
		'type' => 'password',
		'label' => 'Password',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => 'default value',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-text-date',
		'type' => 'date',
		'label' => 'Date',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => 'default value',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-text-date-range',
		'type' => 'date-range',
		'label' => 'Date Range',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => 'default value',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-text-date-time',
		'type' => 'date-time',
		'label' => 'Date Time',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => 'default value',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-text-time',
		'type' => 'time',
		'label' => 'Time',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => 'default value',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	/*
	 * Not Working
	 * array(
		'id' => 'form-text-time-range',
		'type' => 'time-range',
		'label' => 'Time Range',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => array(),
		'default' => 'default value',
		'interval' => '15',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	),*/
	[
		'id' => 'form-text-weekdays',
		'type' => 'weekdays',
		'label' => 'Weekdays',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => 'default value',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-text-color',
		'type' => 'color',
		'label' => 'Color',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => '#FFFFFF',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-textarea',
		'type' => 'textarea',
		'label' => 'Textarea',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => '#FFFFFF',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-select',
		'type' => 'select',
		'label' => 'Select',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => '1',
		'options' => ['1' => 'One', '2' => 'Two'], // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-select-raw',
		'type' => 'select-raw',
		'label' => 'Select Raw',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => '1',
		'options' => ['1' => 'One', '2' => 'Two'], // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-dropdown',
		'type' => 'dropdown',
		'label' => 'Dropdown',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => '1',
		'options' => ['1' => 'One', '2' => 'Two'], // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-checkbox',
		'type' => 'checkbox',
		'label' => 'Checkbox',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => '1',
		'options' => ['1' => 'One', '2' => 'Two'], // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-checkbox-inline',
		'type' => 'checkbox-inline',
		'label' => 'Checkbox (Inline)',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => '1',
		'options' => ['1' => 'One', '2' => 'Two'], // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-radio',
		'type' => 'radio',
		'label' => 'Radio',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => '1',
		'options' => ['1' => 'One', '2' => 'Two'], // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-radio-inline',
		'type' => 'radio-inline',
		'label' => 'Radio (Inline)',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => '1',
		'options' => ['1' => 'One', '2' => 'Two'], // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-user',
		'type' => 'user',
		'label' => 'User',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => '1',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-users',
		'type' => 'users',
		'label' => 'Users',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => '1',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-role',
		'type' => 'role',
		'label' => 'Role',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => '1',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-roles',
		'type' => 'roles',
		'label' => 'Roles',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => '1',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-page',
		'type' => 'page',
		'label' => 'Page',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => '1',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-pages',
		'type' => 'pages',
		'label' => 'Pages',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => '1',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-post',
		'type' => 'post',
		'label' => 'Post',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => '1',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-posts',
		'type' => 'posts',
		'label' => 'Posts',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => '1',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-post-type',
		'type' => 'post-type',
		'label' => 'Post Type',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => '1',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-post-types',
		'type' => 'post-types',
		'label' => 'Post Types',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => '1',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-category',
		'type' => 'category',
		'label' => 'Category',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => '1',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-categories',
		'type' => 'categories',
		'label' => 'Categories',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => '1',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-taxonomy',
		'type' => 'taxonomy',
		'label' => 'Taxonomy',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => '1',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-taxonomy-terms',
		'type' => 'taxonomy-terms',
		'label' => 'Taxonomy Terms',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => '1',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-tag',
		'type' => 'tag',
		'label' => 'Tag',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => '1',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-tags',
		'type' => 'tags',
		'label' => 'Tags',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => '1',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-code-css',
		'type' => 'code-css',
		'label' => 'CSS Code',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => '1',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-code-html',
		'type' => 'code-html',
		'label' => 'CSS HTML',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => '1',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-code-js',
		'type' => 'code-js',
		'label' => 'CSS JS',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => '1',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-wysiwyg',
		'type' => 'wysiwyg',
		'label' => 'wysiwyg',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-wysiwyg-tiny',
		'type' => 'wysiwyg-tiny',
		'label' => 'wysiwyg Tiny',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-file',
		'type' => 'file',
		'label' => 'File',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => '',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-files',
		'type' => 'files',
		'label' => 'Files',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => '',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-user_avatar',
		'type' => 'user_avatar',
		'label' => 'User Avatar',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-file-raw',
		'type' => 'file-raw',
		'label' => 'File Raw',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-sortable',
		'type' => 'sortable',
		'label' => 'Sortable',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => [
			'one',
			'two',
			'three',
			'four'
		],
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-repeatable',
		'type' => 'repeatable',
		'label' => 'Repeatable',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-css-shorthand',
		'type' => 'css-shorthand',
		'label' => 'CSS Shorthand',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-button-with-icon',
		'type' => 'button-with-icon',
		'label' => 'Button With Icon',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-gradient',
		'type' => 'gradient',
		'label' => 'Gradient',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-nav-menu',
		'type' => 'nav-menu',
		'label' => 'Nav Menu',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-sidebar',
		'type' => 'sidebar',
		'label' => 'Sidebar',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-user-meta-key-value',
		'type' => 'user-meta-key-value',
		'label' => 'User Meta Key Value',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-post-meta-key-value',
		'type' => 'post-meta-key-value',
		'label' => 'Post Meta Key Value',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-icon',
		'type' => 'icon',
		'label' => 'Icon',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-responsive-columns',
		'type' => 'responsive-columns',
		'label' => 'Responsive Columns',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
		'options' => 'postmeta', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-country',
		'type' => 'country',
		'label' => 'Country',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
		'options' => 'postmeta', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-aos',
		'type' => 'aos',
		'label' => 'AOS',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
		'options' => 'postmeta', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-font-styles',
		'type' => 'font-styles',
		'label' => 'Font Styles',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-css-styles',
		'type' => 'css-styles',
		'label' => 'CSS Styles',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-min-max',
		'type' => 'min-max',
		'label' => 'Min Max',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-taxonomies',
		'type' => 'taxonomies',
		'label' => 'Taxonomies',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => '1',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-multi-dropdown',
		'type' => 'multi-dropdown',
		'label' => 'Multi Dropdown',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => '1',
		'options' => ['1' => 'One', '2' => 'Two'], // array in case of dropdown, checkbox and radio buttons
	],
	[
		'id' => 'form-font-family',
		'type' => 'font-family',
		'label' => 'Font Family',
		'info' => 'Info goes here',
		'prefix' => 'prefix',
		'suffix' => 'suffix',
		'params' => [],
		'default' => '1',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	],
];

echo '<form action="" method="post">';
echo $this->helpers->renderAdminForm($options);
echo '</form>';
