<?php
return [
	'id' => 'wp-builder',
	'name' => __( 'WP Builder', 'wp-builder-locale' ),
	'theme_name' => __( 'WP Builder', 'wp-builder-locale' ),
	'version' => CJWPBLDR_VERSION,
	'cjwpbldr_website_url' => CJWPBLDR_WEBSITE_URL,
	'cjwpbldr_api_url' => CJWPBLDR_API_URL,
	'cjwpbldr_cloud_api_url' => trailingslashit( CJWPBLDR_API_URL ) . 'addon-wpbuilder-shop/',
	'cjwpbldr_tools_url' => CJWPBLDR_TOOLS_URL,
	'cjwpbldr_tools_api_url' => CJWPBLDR_TOOLS_API_URL,
	'text_domain' => 'wp-builder-locale',
	'description' => __( 'Our base framework enables required shareable resources that are used by all our WordPress products.', 'wp-builder-locale' ),
	'page_title' => __( 'WP Builder', 'wp-builder-locale' ),
	'menu_title' => __( 'WP Builder', 'wp-builder-locale' ),
	'logo_svg' => '',
	'page_slug' => 'cjwpbldr',
	'options_table' => 'cjwpbldr_options',
	'screenshot' => dirname( dirname( __FILE__ ) ) . '/screenshot.png',
	/* URLs */
	'author_url' => 'https://getwpbuilder.com',
	'shop_url' => 'https://getwpbuilder.com/shop',
	'contact_url' => 'https://getwpbuilder.com/contact',
	'support_url' => 'https://wpbuilder.support',
	'affiliates_url' => 'https://getwpbuilder.com/affiliate-program',
	'docs_url' => 'https://getwpbuilder.com/docs',
	'faqs_url' => 'https://getwpbuilder.com/docs-category/faqs/',
	'demo_url' => 'http://demo.getwpbuilder.com/default-theme/',
	'change_log_url' => 'https://getwpbuilder.com/docs',
	'last_updated' => date( 'Y-m-d' ),
	'hire_us_url' => 'https://www.upwork.com/o/companies/~0177f4dc744371fca0',
	'twitter_url' => 'https://twitter.com/getwpbuilder',
	'facebook_url' => 'https://www.facebook.com/getwpbuilder/',
];